apiVersion: v1
kind: Secret
metadata:
  name: tailscale-oauth
  namespace: tsdnsreflector
type: Opaque
data:
  # Base64 encoded OAuth client credentials
  # Replace these with your actual OAuth client credentials
  # Example: echo -n "tskey-client-your-client-id" | base64
  client_id: dHNrZXktY2xpZW50LWV4YW1wbGU=  # Example: tskey-client-example
  client_secret: eW91ci1jbGllbnQtc2VjcmV0  # Example: your-client-secret
---
# Alternative: Secret with traditional auth key
# Use either OAuth secret above OR auth key secret below, not both
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth-traditional
  namespace: tsdnsreflector
type: Opaque
data:
  # Base64 encoded traditional auth key
  # Example: echo -n "tskey-auth-your-auth-key" | base64
  authkey: dHNrZXktYXV0aC1leGFtcGxl  # Example: tskey-auth-example