apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsdnsreflector
  namespace: tsdnsreflector
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "patch", "update"]
  resourceNames:
  - "tailscale-auth"
  - "tsdnsreflector-0"
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tsdnsreflector
  namespace: tsdnsreflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tsdnsreflector
subjects:
- kind: ServiceAccount
  name: tsdnsreflector
  namespace: tsdnsreflector