apiVersion: v1
kind: Service
metadata:
  name: tsdnsreflector
  namespace: tsdnsreflector
spec:
  selector:
    app: tsdnsreflector
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP