---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsdnsreflector-config
data:
  site_id: "1"
  reflected_domain: "cluster1.local"
  original_domain: "cluster.local"
  # Optional: custom DNS resolver in the format "host:port"
  # dns_resolver: "8.8.8.8:53" 
  # Optional: force 4via6 mode
  force_4via6: "true"