name: Docker

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        run: |
          # Set image name
          IMAGE=ghcr.io/${{ github.repository }}
          
          # Determine tags
          TAGS="--tag $IMAGE:latest"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="$TAGS --tag $IMAGE:$VERSION"
          fi
          
          # Build and push multi-arch image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            $TAGS \
            --push \
            .